# Application Configuration
replicaCount: 1

image:
  repository: ghcr.io/sajjadghf/crypto-exchange
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: demo.iransre.ir
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 10m
    memory: 100Mi

# Django Application Settings
django:
  debug: "False"
  secretKey: "CHANGE_ME_IN_PRODUCTION"
  allowedHosts: "demo.iransre.ir"

# PostgreSQL Configuration
postgresql:
  # Write instance (master)
  write:
    enabled: true
    replicaCount: 1
    image:
      repository: postgres
      tag: "15-alpine"
    persistence:
      enabled: false
      size: 10Gi
      storageClass: ""
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 10m
        memory: 100Mi
    database: crypto_exchange
    username: exchange_user
    # Password should be provided via secret or values override
    password: "CHANGE_ME_IN_PRODUCTION"
    port: 5432

  # Read replicas
  read:
    enabled: true
    replicaCount: 2
    image:
      repository: postgres
      tag: "15-alpine"
    persistence:
      enabled: false
      size: 10Gi
      storageClass: ""
    resources:
      limits:
        cpu: 10m
        memory: 100Mi
      requests:
        cpu: 10m
        memory: 100Mi
    port: 5432

# Persistence for media files
persistence:
  enabled: false
  storageClass: ""
  accessMode: ReadWriteMany
  size: 5Gi

nodeSelector: {}

tolerations: []

affinity: {}
