# Application Configuration
replicaCount: 1

image:
  repository: ghcr.io/sajjadghf/crypto-exchange
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: demo.iransre.ir
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 10m
    memory: 100Mi

# Django Application Settings
django:
  debug: "False"
  secretKey: "CHANGE_ME_IN_PRODUCTION"
  allowedHosts: "*"

# PostgreSQL Configuration
postgresql:
  # Write instance (master)
  write:
    enabled: true
    replicaCount: 1
    image:
      repository: postgres
      tag: "15-alpine"
    persistence:
      enabled: false
      size: 10Gi
      storageClass: ""
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 10m
        memory: 100Mi
    database: crypto_exchange
    username: exchange_user
    # Password should be provided via secret or values override
    password: "CHANGE_ME_IN_PRODUCTION"
    port: 5432

  # Read replicas
  read:
    enabled: true
    replicaCount: 2
    image:
      repository: postgres
      tag: "15-alpine"
    persistence:
      enabled: false
      size: 10Gi
      storageClass: ""
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 10m
        memory: 100Mi
    port: 5432

# Database Backup Configuration
backup:
  enabled: true
  # Cron schedule (default: daily at 2 AM)
  schedule: "0 2 * * *"
  # Number of backups to retain
  retention: 7
  # Backup storage configuration
  persistence:
    enabled: false
    size: 20Gi
    storageClass: ""
  # HostPath configuration (used when persistence is disabled)
  hostPath: "/var/backups/crypto-exchange"
  # Job history limits
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 10m
      memory: 10Mi

# Persistence for media files
persistence:
  enabled: false
  storageClass: ""
  accessMode: ReadWriteMany
  size: 5Gi

nodeSelector: {}

tolerations: []

affinity: {}
