{{- if and .Values.backup.enabled .Values.backup.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "crypto-exchange.fullname" . }}-backup
  labels:
    {{- include "crypto-exchange.labels" . | nindent 4 }}
    app.kubernetes.io/component: backup
spec:
  accessModes:
  - ReadWriteOnce
  {{- if .Values.backup.persistence.storageClass }}
  storageClassName: {{ .Values.backup.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.backup.persistence.size }}
{{- end }}
