apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "crypto-exchange.fullname" . }}-config
  labels:
    {{- include "crypto-exchange.labels" . | nindent 4 }}
data:
  init-db.sh: |
    #!/bin/bash
    set -e
    
    echo "Waiting for PostgreSQL to be ready..."
    until pg_isready -h {{ include "crypto-exchange.postgresql.write.fullname" . }} -U {{ .Values.postgresql.write.username }}; do
      echo "Waiting for database..."
      sleep 2
    done
    
    echo "Running migrations..."
    python manage.py migrate --noinput
    
    echo "Collecting static files..."
    python manage.py collectstatic --noinput || true
    
    echo "Database initialization complete!"
